In [19]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
print(a.shape)
print(a.dtype.name)
print(a.itemsize)
print(a.size)

(3, 5)
int32
4
15


In [8]:
b = np.array([6, 7, 8])
print(b)

[6 7 8]


In [15]:
c = np.array([1, "two", 3, 4])
print(c.dtype.name)

str352


In [23]:
a = np.array([1.2, 3.5, 5.1])
print(a.dtype)

float64


In [24]:
a = [2, 4, 5]
print(a)
a

[2, 4, 5]


[2, 4, 5]

In [29]:
aa = np.array(a)
print(aa)
print(aa[1])
print(a[1])
aa

[2 4 5]
4
4


array([2, 4, 5])

In [33]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


In [34]:
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [39]:
arr_slice = arr[5:8]
print(arr_slice)

arr_slice[1] = 12345
print(arr)

arr_slice[:] = 64
print(arr)

[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]
[ 0  1  2  3  4 64 64 64  8  9]


In [42]:
arr_slice_copy = arr[5:8].copy()
print(arr_slice_copy)
print(arr)

arr_slice_copy[:] = 8
print(arr_slice_copy)
print(arr)

[64 64 64]
[ 0  1  2  3  4 64 64 64  8  9]
[8 8 8]
[ 0  1  2  3  4 64 64 64  8  9]


In [52]:
a1 = np.array([1, 2, 3, 4, 5, 6])
ab1 = np.array((1, 2, 3, 4, 5, 6))

print(a1)
print(ab1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
a2 = np.zeros(3)  # 1행 3열의 0으로 된 1차원 배열 vector 생성
print(a2)

a3 = np.ones(3)  # 1행 3열의 1로 된 1차원 배열 vector 생성
print(a3)

a4 = np.arange(1, 7, 1)  # 1부터 6까지 1씩 증가하는 1차원 배열 vector 생성
print(a4)

k1 = np.eye(3)  # 3행 3열의 단위행렬(identity matrix) 생성
print(k1)

[0. 0. 0.]
[1. 1. 1.]
[1 2 3 4 5 6]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
z = np.zeros(5)
o = np.ones([2, 3, 4])
n = np.eye(3)

print(z)
print("\n--------------------\n")
print(o)
print("\n--------------------\n")
print(n)

[0. 0. 0. 0. 0.]

--------------------

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

--------------------

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [80]:
print(a1)
print(a1.ndim)
print(a1.shape)

a1.shape = (2, 3)  # 2행 3열로 변경
print(a1)

a1.shape = (3, 2)  # 3행 2열로 변경
print(a1)

a1.shape = (6, 1)  # 6행 1열로 변경
print(a1)

a1.shape = (1, 6)  # 1행 6열로 변경 = a1.shape(6,)
print(a1)

[1 2 3 4 5 6]
1
(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [91]:
k = np.random.random((2, 3))
print(k)

[[0.28067442 0.6759884  0.03461038]
 [0.74317534 0.99274273 0.16308069]]


In [84]:
f = np.full((2, 2), 7)  # 2행 2열의 모든 원소가 7인 배열 생성
print(f)

[[7 7]
 [7 7]]


In [100]:
na = np.array([1, 2, 3, 4, 5, 6, 7, 8])
na2 = na.reshape(2, 4)
print(na2[1, 1])
print(na2[1][1])

6
6


In [ ]:
array = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
        [[0, 1, 2, 3], [4, 5, 100, 7], [8, 9, 10, 11]],
    ]
)

print(array, array.shape)
# 배열의 가장 바깥 부분 대괄호 개수를 보면 해당 array가 몇 차원인지 알 수 있다. 예) 3개 -> 3차원

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]] (2, 3, 4)


In [111]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print("\n--------------------\n")

print(x - y)
print(np.subtract(x, y))

print("\n--------------------\n")

print(x * y)
print(np.multiply(x, y))

print("\n--------------------\n")

print(x / y)
print(np.divide(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

--------------------

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

--------------------

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]

--------------------

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [120]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#  벡터의 내적
print(v @ w)
print(v.dot(w))
print(np.dot(v, w))

print("")
#  행렬과 벡터의 곱
print(x @ v)
print(x.dot(v))
print(np.dot(x, v))

print("")
#  행렬곱
print(x @ y)
print(x.dot(y))
print(np.dot(x, y))

219
219
219

[29 67]
[29 67]
[29 67]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [123]:
a = [1, 2, 3]
b = [3, 4, 5]

print(type(a))
print(2 * a)
print(a + b)

<class 'list'>
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 3, 4, 5]


In [124]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

print(type(a))
print(2 * a)
print(a + b)

<class 'numpy.ndarray'>
[2 4 6]
[4 6 8]


In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6]])

print(c.size)
print(c.shape)

6
(2, 3)


In [ ]:
np.arange(10).reshape(2, 5)  #  0부터 9까지의 정수 배열을 생성 후 2행 5열로 변환

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(2, 3, 0.1)  # 2부터 3까지 0.1씩 증가하는 배열 생성

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.linspace(1.0, 4.0, 6)  # 1.0부터 4.0까지 6개로 나누어 생성

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
np.zeros((2, 2), int)

array([[0, 0],
       [0, 0]])

In [ ]:
np.zeros((2, 2), float)

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2, 2))  # 2행 2열의 모든 원소가 1인 float 배열 생성

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.full((2, 2), 7)  # 2행 2열의 모든 원소가 7인 배열 생성

array([[7, 7],
       [7, 7]])

In [ ]:
np.eye(4)  # 4행 4열의 단위행렬(identity matrix) 생성

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.random((2, 3))  # 2행 3열의 0에서 1 사이의 랜덤한 실수 배열 생성

array([[0.56334212, 0.79700955, 0.64166462],
       [0.85852649, 0.94485164, 0.58876427]])

In [ ]:
np.random.randint(1, 10, (2, 3))  # 1부터 10까지의 정수 중에서 랜덤한 2행 3열 배열 생성

array([[2, 5, 5],
       [6, 9, 1]])

In [155]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
print(a[0, 0])
print(a[(0, 0)])
print(a[1, 2])

1
1
7


In [156]:
print(a[-1, -1])
a[-1, -1] += 10  # 마지막 원소에 10을 더함
print(a)

12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 22]]


In [ ]:
print(a[1, :])  # 1행 전체를 출력
print(a[:, 1])  # 1열 전체를 출력
print(a[:2, :])  # 0행과 1행을 출력

[5 6 7 8]
[ 2  6 10]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(a[:, 0:3:2])  # 모든 행에 대해서, 0열부터 3열까지 2열 간격으로 출력

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [ ]:
print(a > 5)
print(a[a > 5])  # 5보다 큰 원소만 출력

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 22]


In [ ]:
b = a[:]  # shallow copy: 얕은 복사(원본에 영향을 미침)

b[b % 2 == 0] += 100  # 짝수인 원소에 100을 더함
print(b)

[[  1 102   3 104]
 [  5 106   7 108]
 [  9 110  11 122]]


In [164]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.arange(11, 17).reshape(2, 3)

print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


In [166]:
print(c**2)
print(np.sqrt(c))

[[ 1  4  9]
 [16 25 36]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [167]:
print(np.dot(c, d.transpose()))  # c와 d의 내적

[[ 74  92]
 [182 227]]


In [168]:
print(np.dot(c.T, d))

[[ 67  72  77]
 [ 92  99 106]
 [117 126 135]]


In [ ]:
list1 = [3, 5.6, 5, 8, 9.5]

array = np.array(list1)

print(array.var())  # 분산 (variance)
print(array.std())  # 표준편차 (standard deviation)
print(array.mean())  # 평균 (mean)
print(array.sum())  # 합계 (sum)
print(array.max())  # 최댓값 (maximum)
print(array.min())  # 최솟값 (minimum)

5.233600000000001
2.287706274852609
6.220000000000001
31.1
9.5
3.0


In [179]:
ar1 = np.array([1, 2, 3])
print("자료형 type:", ar1.dtype)  # int32

자료형 type: int32


In [ ]:
ar2 = np.array(["12", "2", "3"])
print("자료형 type:", ar2.dtype)  # Unicode string

자료형 type: <U2


In [177]:
ar3 = np.array([1.5, 2.0, 3.5])
print("자료형 type:", ar3.dtype)  # float64

자료형 type: float64


In [180]:
ar4 = np.array([1, 2.9, 3, "4"])
print(ar4)
print("자료형 type:", ar4.dtype)  # Unicode string

['1' '2.9' '3' '4']
자료형 type: <U32


In [187]:
ar5 = np.array([False, False, True, False], dtype=np.int32)
print(ar5)
print(f"자료형 type: {ar5.dtype}")  # int32

[0 0 1 0]
자료형 type: int32


In [188]:
print(np.argmax(ar5))  # 최댓값의 인덱스

2


In [189]:
from numpy import argmax

print(argmax(ar5))

2


In [ ]:
# 1. 숫자 15에서 23까지 배열을 만들고 이를 3*3 행렬로 변환하여 출력하라.


no1 = np.arange(15, 24).reshape(3, 3)
print(no1)

[[15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
# 2. 다음의 두 array를 만들고,
# [1, 2, 3, 4], [5, 6, 7, 8]
# 두 array를 이용해서 아래와 같은 값이 나오게 하라.
# [False, False, False, False]


no2_1 = np.array([1, 2, 3, 4])
no2_2 = np.array([5, 6, 7, 8])

no2 = list(no2_1 == no2_2)
print(no2)

[False, False, False, False]


In [ ]:
# 3. 아래와 같이 세 학생의 중간고사, 기말고사, 과제 점수가 있다.
# (철수, 영희, 민재)
# 중간고사: (15, 100, 45)
# 기말고사: (78, 25, 90)
# 과제: (81, 45, 99)

# 중간, 기말, 과제 점수에 각각 0.4, 0.4, 0.2의 가중치를 부여하여 가중치의 합을 구하고, 거기에 기타 점수 5점을 더하고자 한다.
# 이를 array를 이용해 계산하는 프로그램을 작성하라.
# 요구사항
# 1) 중간고사 평균과 표준 편차를 출력하라.
# 2) 철수의 최종 점수는 얼마인지 출력하라.


mid = np.array([15, 100, 45])
final = np.array([78, 25, 90])
assignment = np.array([81, 45, 99])
weight = np.array([0.4, 0.4, 0.2])
other_score = 5

total_score = mid * weight[0] + final * weight[1] + assignment * weight[2] + other_score

print(f"1) 중간고사 평균: {mid.mean():.2f}, 표준 편차: {mid.std()}")
print(f"2) 철수의 최종 점수: {total_score[0]:.1f}")

1) 중간고사 평균: 53.33, 표준 편차: 35.19785346990479
2) 철수의 최종 점수: 58.4


In [43]:
# 1. 1차원 배열 생성 및 연산
# 1) 숫자 10부터 30까지의 배열을 생성하고, 배열 내 모든 값에 2를 곱한 결과를 출력하세요.
import numpy as np

question1 = np.arange(10, 31)
print(question1)
print(question1 * 2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [ ]:
# 2. 다차원 배열 생성 및 변환
# 1) 숫자 0부터 15까지 포함하는 1차원 배열을 생성하세요.
# 2) 이 배열을 4x4 2차원 행렬로 변환하세요.

question2_1 = np.arange(16)
print(question2_1)

question2_2 = question2_1.reshape(4, 4)
print(question2_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# 3. 특정 조건에 맞는 값 필터링
# 1) 1부터 20까지의 배열에서 짝수만 추출하여 새 배열을 생성하세요.

question3_1 = np.arange(1, 21)
print(question3_1)

question3_even = question3_1[question3_1 % 2 == 0]
print(question3_even)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [65]:
# 4. 배열 연산 및 집계 함수 활용
# 1) 임의의 3*3 배열을 생성하세요.
# 2) 배열의 각 행의 합계와 평균을 구하고 출력하세요.

question4_1 = np.random.randint(1, 10, (3, 3))
print(question4_1)

question4_sum = question4_1[:, 0] + question4_1[:, 1] + question4_1[:, 2]
question4_mean = question4_sum / len(question4_1[0])  # 각 행의 평균

for i in range(len(question4_1)):
    print(f"{i + 1}행의 합계: {question4_sum[i]}, 평균: {question4_mean[i]:.2f}")


# --------------------------------------------------

question4_sum2 = question4_1.sum(axis=1)  # 각 행의 합계
question4_mean2 = question4_sum2 / question4_1.shape[1]  # 각 행의 평균
for i in range(len(question4_1)):
    print(f"{i + 1}행의 합계: {question4_sum2[i]}, 평균: {question4_mean2[i]:.2f}")

[[7 6 5]
 [8 8 2]
 [2 1 7]]
1행의 합계: 18, 평균: 6.00
2행의 합계: 18, 평균: 6.00
3행의 합계: 10, 평균: 3.33
1행의 합계: 18, 평균: 6.00
2행의 합계: 18, 평균: 6.00
3행의 합계: 10, 평균: 3.33


In [66]:
# 5. 행렬 곱셈 및 정규화
# 1) 3*3 단위 행렬(identity matrix)을 생성하세요.
# 2) 다른 3*3 행렬을 만들어 행렬의 곱을 구하세요.

question5_1 = np.eye(3)
print(question5_1)

question5_2 = np.random.randint(1, 10, (3, 3))
print(question5_2)

question5_matmul = question5_1 @ question5_2
print(question5_matmul)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5 6 4]
 [2 8 5]
 [6 5 5]]
[[5. 6. 4.]
 [2. 8. 5.]
 [6. 5. 5.]]
